name: Linter

on: 
    push:
        branches:
            - dashboard_feature

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        # Set up Node.js for Angular frontend
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
              node-version: '14'

        - name: Install frontend dependencies
          run: npm install
          working-directory: ./Frontend

        - name: Run Angular linter
          run: npm run lint
          working-directory: ./Frontend

        # Set up Go for backend
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
              go-version: '1.16'

        - name: Install backend dependencies
          run: go mod tidy
          working-directory: ./Backend

        - name: Run Go linter
          run: golangci-lint run
          working-directory: ./Backend
